---
- name: Configure Cisco Routers
  gather_facts: True
  hosts: routers
  connection: network_cli

  tasks:
    - name: Changing password of username "AVINASH"
      ios_config:
        save_when: modified
        lines:
          - username avinash privi 15 secre C1sc0*()
      register: output

    - name: Print the output
      debug: var=output
