---
- name: Configure Cisco Routers
  gather_facts: True
  hosts: routers
  connection: network_cli
  #####################################################################################
  ###### Behavioral Inventory Parameters are stored at "group_vars\routers.yml" #######
  #####################################################################################

  vars_prompt:
    - name: uname
      prompt: "Enter Your Username" # Promp the message while asking for user's input
      private: no # Make the text visible to users
    - name: passwd
      prompt: "Enter Your Password"
      private: yes # Make the text invisible to users
      unsafe: yes # Allows special characters input by user. Its required especially in passwords.
    - name: enable_pass
      prompt: "Enter 'enable' Password"
      private: yes
      unsafe: yes
  tasks:
    - name: Changing password of username "AVINASH"
      ios_config:
        save_when: modified
        lines:
          - username avinash privi 15 secre 123ccna*()
      register: output

    - name: Print the output
      debug: var=output
