---
- name: Gather IOS-XE Facts
  hosts: ios-xe-mgmt-latest.cisco.com
  connection: local
  tasks:
      - name: Gather IOS Facts
        ios_facts:
            provider:
                host: ios-xe-mgmt-latest.cisco.com
                port: 22
                authorize: yes
                auth_pass: C1sco12345
                username: developer
                password: C1sco12345

      - name: What is the IOS OS Verion?
        debug:
            var: ansible_net_version

      - name: What is the hostname?
        debug:
            var: ansible_net_hostname
#### Other usefule Variables from the facts ####
# ansible_net_config
# ansible_net_model
# ansible_net_serialnum
# ansible_net_image
# ansible_net_all_ipv4_addresses
# ansible_net_all_ipv6_addresses
# ansible_net_neighbors
# ansible_net_interfaces
# ansible_net_memfree_mb
# ansible _net_memtotal_mb
