---
- name: Issue show commands
  hosts: 172.16.1.25
  connection: local
  tasks:
      - name: Show ip interface brief
        ios_command:
            commands:
                - show ip inter brief
            provider:
                host: 172.16.1.25
                port: 22
                authorize: yes
                auth_pass: cisco
                username: cisco
                password: cisco
            register: if_data

      - name: Interfaces Output
        debug:
            var: if_data['stdout_ines'][0]
