---
- hosts: hosts
  become: yes
  tasks:
    - name: install vsftpd on centos
      yum: name=vsftpd update_cache=yes state=latest
      ignore_errors: yes
      notify: start vsftpd

  handlers:
    - name: start vsftpd
      service: name=vsftpd enabled=yes state=started
