---
- hosts: hosts
  vars:
    - var1: cool stuff here
    - var2: cool stuff 2

  tasks:
    - name: echo stuffs
      shell: echo "{{ var1 }} is var1, but var2 is {{ var2 }}" > file.txt
      shell: echo "OS Family is {{ ansible_os_family }} " >> file.txt          # "ansible_os_family" is the variable ansible collects while doing FACT CHECKS on remote hosts.
