---
- hosts: hosts
  become: yes

  tasks:
      - name: Install stuff
        yum: name={{item}} update_cache=yes state=latest
        ignore_errors: yes
        with_items:
            - vim
            - nano
            - httpd
      - name: Show file contents
        debug: msg={{item}}
        with_file:
            - /root/ansible/file1.txt
            - /root/ansible/file2.txt
      - name: Show file contents
        debug: msg="This is loop# {{item}}"
        with_sequence: start=1 end=10
