---
- name: Install on Debian
  apt: name=apache2 satate=latest update_cache=yes
  when: ansible_os_family == "Debian"

- name: Install on CentOS
  yum: name=httpd state=latest update_cache=yes
  when: ansible_os_family == "RedHat"

- name: Start Debian Service
  service: name=apache2 enabled=yes state=started
  when: ansible_os_family == "Debian"

- name: Start CentOS Service
  service: name=httpd enabled=yes state=started
  when: ansible_os_family == "RedHat"
